[tool.poetry]
name = "multiagent"
version = "0.1.0"
description = ""
authors = ["aruns05 <arun.s2k8@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
